import type { Metadata } from "next";
import "./globals.css";

import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Extensions",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const prefCookie = cookieStore.get("data_theme")?.value;

  const initialPrefs = prefCookie
    ? JSON.parse(prefCookie)
    : { theme: "light", locale: "pt-BR" };

  return (
    <html lang="en" className={`${initialPrefs.state.theme}`}>
      <body className="antialiased font-display">{children}</body>
    </html>
  );
}
