import type { Metadata } from "next";
import "./globals.css";

import { cookies } from "next/headers";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Extensions",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const prefCookie = cookieStore.get("data_theme")?.value;

  const theme = prefCookie
    ? JSON.parse(prefCookie).state.data_theme?.value
    : "light";

  return (
    <html lang="en" className={`${theme}`}>
      <body className="flex justify-center font-display bg-linear-to-b from-light-gradient-from to-light-gradient-to dark:from-dark-gradient-from dark:to-dark-gradient-to min-h-lvh min-w-[300px] ">
        <div className="max-w-7xl w-full px-5 pt-4">
          <Header />

          {children}
        </div>
      </body>
    </html>
  );
}
